### ISSUE TITLE
Update 5.9.0 | Droid Infantry

### ISSUE THREAD

**Issue by xxQal** [91st-Aux-Team/MRC-issue-tracker#69]
**Describe the bug**
- The New B2s are Spawning with Vanilla "Items" in the Uniform.
- The B2 GL Varrients Have GL Mags Listed with "10 Rockets" can only Fire 4 before Reload.
- The B2 "Non"GL Varrients are Spawning with the GL Ammo.
-The B1 Assault has an Innitial "Arming" time that only happens once on Pull out of the E60R-AT Launcher. After this first "arming" time it does not Repeat on Requip OR Reloading.

**To Reproduce**
Spawn the Units in.
Use the E60R-AT

**Expected behavior**
B2s not Spawn with "Vanilla" Equipment & The Other 2 are more Nit Picky.

**Screenshots**
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/612bb931-5b6b-4c2d-8295-4e22a97d8a82)
![image](https://github.com/91st-Aux-Team/MRC-issue-tracker/assets/139514961/edf0f75d-6caf-4e9c-9034-290b73e8cf5a)

**Mod List**
Main Op Pinned in Main Discord.

**Additional context**

**Comment by Durzai** [comment]
- B2 Vanilla Items Removed.
- B2 Rhine Wrist Rockets count renamed from 10 to 4.
- Normal B2 has Rhine Wrist Rockets removed from backpack.
- The initial arming period of the rocket launcher is inherent to Arma, it is to stop freshly spawned rocket units from instantly firing. We can't add that kind of cooldown between their shots, so that will have to stay as it is.
